# This workflow will add any newly created issue to the "ICYOA" project.
# It is triggered whenever a new issue is opened in the repository.
name: Add New Issue to ICYOA Project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add Issue to Project
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/vedantm8/projects/3 
          column-name: "Backlog" 
          github-token: ${{ secrets.GITHUB_TOKEN }}
